import regex as re
from typing import Optional, Iterable, Iterator
from .bpe_common import COMPILED_PRETOKEN_RE, BYTE_TABLE, load_bpe_merges, load_bpe_vocab

def split_on_special_tokens(corpus: str, special_tokens: list[str]) -> list[str]:
    """
    Split the text on special tokens so that we don't merge across
    document boundaries. The returned list also includes the special tokens
    used for the split.
    For example
    ```
    split_on_special_tokens("the<|endoftext|> cat ate", ["<|endoftext|>"])
    -> ["the", "<|endoftext|>", " cat ate"]
    """

    # escape the pipe | character in the regex since it's a special regex char
    # wrap the special tokens in capturing groups in the regex so that they can be included
    # in the re.split result
    escaped_special_tokens = [
        "(" + token.replace('|', '\\|') + ")" for token in special_tokens]
    
    return filter(lambda x: x is not None and len(x) > 0, re.split("|".join(escaped_special_tokens), corpus))

def get_utf8_bytes_tuple(text: str) -> tuple[bytes]:
    encoded = text.encode("utf-8")
    return tuple(BYTE_TABLE[b] for b in encoded)

def try_merge(pretoken: tuple[bytes], merge: tuple[bytes, bytes]) -> Optional[tuple[bytes]]:
    t1, t2 = merge
    merged = t1 + t2

    temp_new_tokens: list[bytes] = None
    length = len(pretoken)

    # Find first occurence of pair to merge, then create new temp list
    i = 0
    while i < length - 1:
        if pretoken[i] == t1 and pretoken[i + 1] == t2:
            temp_new_tokens = [item for item in pretoken[:i]] # copy all previous bytes
            temp_new_tokens.append(merged)
            i += 2
            break
        i += 1
    
    if temp_new_tokens:
        # i is positioned right after the first merged pair
        while i < length:
            new_i = len(temp_new_tokens) - 1
            if temp_new_tokens[new_i] == t1 and pretoken[i] == t2:
                temp_new_tokens[new_i] = merged
            else:
                temp_new_tokens.append(pretoken[i])
            i += 1
        
        return tuple(temp_new_tokens)
    

class Tokenizer:
    def __init__(self, vocab: dict[int, bytes], merges: list[tuple[bytes, bytes]], special_tokens: list[str]|None = None):
        self.vocab = vocab
        self.token_ids = { token : id for id, token in vocab.items() }
        self.merges = merges

        # Sort the special tokens in desending order of length so
        # we can properly handle overlapping sequences by making sure
        # the longer match is detected first in the regex split
        # i.e. if we have special_tokens = ['<|foo|>', '<|foo|><|foo|>']
        # and input text 'bar<|foo|><|foo|>', we want <|foo|><|foo|> to
        # be matched, instead of <|foo|>.
        self.special_tokens = sorted(special_tokens, key=lambda x: -len(x)) if special_tokens else None
    
    @classmethod
    def from_files(cls, vocab_file_path: str, merges_file_path: str, special_tokens: list[str]|None = None) -> 'Tokenizer':
        """
        Class method that constructs and return a Tokenizer from a serialized vocabulary and list of merges
        and (optionally) a list of special tokens. The files should be in the same format
        generated by bpe_common.dump_bpe_vocab and bpe_common.dump_bpe_merges respectively.
        """
        vocab = load_bpe_vocab(vocab_file_path)
        merges = load_bpe_merges(merges_file_path)
        return Tokenizer(vocab, merges, special_tokens)

    def encode(self, text: str) -> list[int]:
        """
        Encode an input text into a sequence of token IDs.
        """
        segments = split_on_special_tokens(text, self.special_tokens) if self.special_tokens else [text]
        # Each pretoken is encoded independently, we don't perform
        # any merges across pretoken boundaries
        # TODO: this means we can process pretokens in parallel
        result = [token for segment in segments for pretoken in self._pretokenize(segment) for token in self._encode_pretoken(pretoken)]
        return result
    
    def encode_iterable(self, iterable: Iterable[str], chunk_size:int = 4096) -> Iterator[int]:
        """
        Given an iterable of strings (e.g., a Python file handle),
        return a generator that lazily yields token IDs.
        This is required for memory-eﬀicient tokenization of large files
        that we cannot directly load into memory.
        """
        return IterableEncoderIterator(self, iter(iterable), chunk_size)

    def decode(self, ids: list[int]) -> str:
        """
        Decode a sequence of token IDs into text
        """
        byte_seq = b''
        for id in ids:
            byte_seq += self.vocab[id]
        
        # Replace invalid/malformed byte sequences with Unicode replace char U+FFFD
        # See: https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character
        decoded = bytes.decode(byte_seq, "utf-8", errors='replace')
        return decoded

    def _pretokenize(self, text: str) -> list[tuple[bytes]]:
        if self.special_tokens and text in self.special_tokens:
            # If it's a special token, return it as is since we won't merge it.
            result = [(text.encode('utf-8'),)]
            return result
        
        pretokens = COMPILED_PRETOKEN_RE.finditer(text)
        result = [get_utf8_bytes_tuple(match.group(0)) for match in pretokens]
        return result

    def _encode_pretoken(self, pretoken: tuple[bytes]) -> list[int]:
        result = pretoken
        for merge in self.merges:
            merge_result = try_merge(result, merge)
            if merge_result is not None:
                result = merge_result
                # short-circuit if the result is only 1 token
                if len(result) == 1:
                    break
        
        encoded = [self.token_ids[token] for token in result]
        return encoded

    
class IterableEncoderIterator:
    def __init__(self, tokenizer: Tokenizer, input_iter: Iterator[str], chunk_size:int = 4096):
        self.tokenizer = tokenizer
        self.input_iter = input_iter
        self.chunk_size = chunk_size
        self.buffer = []
        self.buffer_pos = 0
        self.prev_leftover = []

    def _read_next_chunk(self):
        chunk = [] + self.prev_leftover
        self.prev_leftover = []
        chunk_length = 0

        item = next(self.input_iter, None)
        end_of_stream = item is None
        while not end_of_stream:
            # need to buffer items until it reaches desired chunk size
            # but need make sure it neither crosses special token or pretoken boundary
            chunk.append(item)
            chunk_length += len(item)
            if chunk_length >= self.chunk_size:
                break

            item = next(self.input_iter, None)
            end_of_stream = item is None

        chunk_str = ''.join(chunk)
        if end_of_stream:
            self.buffer = self.tokenizer.encode(chunk_str)
            self.buffer_pos = 0
            return
    
        segments = split_on_special_tokens(chunk_str, self.tokenizer.special_tokens) if self.tokenizer.special_tokens else [chunk_str]
        # if there are multiple segments, move the last segments to leftover, it would be processed with next chunk
        # to ensure we're not at a boundary
        if len(segments) > 1:
            self.prev_leftover.append(segments[-1])
            segments = segments[:-1]
        else:
            # we only have one segment, but it might end at a pretoken boundary. Let's remove
            # the last pretoken
            pretokens = COMPILED_PRETOKEN_RE.findall(segments[0])
            assert len(pretokens) >= 1
            if len(pretokens) > 1:
                # the last pretoken might be at a chunk boundary, let's remove it and process
                # it in the next chunk
                self.prev_leftover = [pretokens[-1]] + self.prev_leftover # TODO optimize
                chunk_str = ''.join(pretokens[:-1]) # TODO optimize
            else:
                # if we only have one pretoken, then the entire chunk might have been split
                # at a boundary, let's buffer what we have and read more data.
                self.prev_leftover = [chunk_str]
                return self._read_next_chunk()

        # TODO: inefficient: we pass the joined chunk_str to the tokenizer,
        # which will split it and pretokenize it again, redundant work
        self.buffer = self.tokenizer.encode(chunk_str)
        self.buffer_pos = 0
    
    def _is_buffer_empty(self):
        return self.buffer_pos >= len(self.buffer)
    
    def __iter__(self) -> Iterator[int]:
        return self

    def __next__(self) -> int:
        if self._is_buffer_empty():
            self._read_next_chunk()
        
        if self._is_buffer_empty():
            # reached end
            raise StopIteration
        
        result = self.buffer[self.buffer_pos]
        self.buffer_pos += 1
        return result

